
alter table choices add column if not exists col_label text;
alter table choices add column if not exists col_type text;
alter table choices add column if not exists col_time_range text;
alter table rounds add column if not exists max_overlap_minutes int default 0;

drop table if exists shift_definitions cascade;
create table if not exists shift_definitions (
  id bigint generated by default as identity primary key,
  title text not null,
  start_col integer not null,
  end_col integer not null
);

create table if not exists exchange_rule_sets (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  is_active boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: In Supabase, if exchange_modes and exchange_rules exist, they need to be updated.
-- If someone runs this file from scratch, this defines the new schema.
create table if not exists exchange_modes (
  id uuid default gen_random_uuid() primary key,
  set_id uuid references exchange_rule_sets(id) on delete cascade not null,
  col_id integer not null,
  mode text not null,
  unique(set_id, col_id)
);

create table if not exists exchange_rules (
  id uuid default gen_random_uuid() primary key,
  set_id uuid references exchange_rule_sets(id) on delete cascade not null,
  source_col_id integer not null,
  source_period text not null,
  target_col_id integer not null,
  target_period text not null
);

create table if not exists shift_global_settings (
  id integer primary key default 1,
  target_substitute_active boolean default false,
  target_substitute_max integer default 0,
  target_doctor_active boolean default false,
  target_doctor_max integer default 0,
  target_substitute_normal_active boolean default false,
  target_substitute_good_active boolean default false,
  target_substitute_bad_active boolean default false,
  target_doctor_normal_active boolean default false,
  target_doctor_good_active boolean default false,
  target_doctor_bad_active boolean default false
);

create table if not exists logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_trigram text,
  action text,
  details jsonb
);

insert into shift_global_settings (id) values (1) on conflict (id) do nothing;

-- SECURITY: Secure Login Function (Alternative to Supabase Auth)
-- Run this in Supabase SQL Editor to create a secure way to check credentials
-- without giving public read access to the 'users' table.
create or replace function login(trigram_input text, password_input text)
returns json as $$
declare
  found_user record;
begin
  select * from users where trigram = trigram_input and password = password_input into found_user;
  if found_user is null then
    return null;
  else
    return row_to_json(found_user);
  end if;
end;
$$ language plpgsql security definer;

-- To secure the users table:
-- 1. Run the function creation above.
-- 2. Revoke public access: REVOKE SELECT ON users FROM anon;
-- 3. Update App.tsx to use: const { data } = await supabase.rpc('login', { trigram_input: '...', password_input: '...' });
