
alter table choices add column if not exists col_label text;
alter table choices add column if not exists col_type text;
alter table choices add column if not exists col_time_range text;

drop table if exists shift_definitions cascade;
create table if not exists shift_definitions (
  id bigint generated by default as identity primary key,
  title text not null,
  start_col integer not null,
  end_col integer not null
);

create table if not exists shift_global_settings (
  id integer primary key default 1,
  target_substitute_active boolean default false,
  target_substitute_max integer default 0,
  target_doctor_active boolean default false,
  target_doctor_max integer default 0
);

insert into shift_global_settings (id) values (1) on conflict (id) do nothing;
